name: coolstore
description: "Ecommerce project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  auto_route: ^10.0.1
  bloc: ^9.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  fade_shimmer: ^2.2.0
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5

  #local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true


  assets:
      - assets/images/
      - assets/icons/
  
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Italic.ttf
          style: italic
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-Regular.ttf
        - asset: assets/fonts/Lora/Lora-Bold.ttf
        - asset: assets/fonts/Lora/Lora-Italic.ttf
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
